### PR TITLE
Use * if to enable all filetypes.

### PR DESCRIPTION
**Pull request by zhaocai**
Like to use the filename completion everywhere

### CODE REVIEW

**Comment by zhaocai** [comment]
Not a good idea. 

Is there anyway to enable specific completer?

**Comment by Qusic** [comment]
Which filetype are you having problems with?

**Comment by zhaocai** [comment]
Thanks for asking. My intentions are the generic completers for filename and identifiers. I would like to enable for all type of files. 

BTW, how do I enable completer for ctags?

**Comment by Qusic** [comment]
Autocomplete+ has already provided completion for filenames and identifiers and it is recommended over the generic completers of ycm.
As for ctags, see here https://github.com/Valloric/YouCompleteMe#the-gycm_collect_identifiers_from_tags_files-option

**Comment by zhaocai** [comment]
Thanks.

**Pull request closed without merging**
